### ISSUE TITLE
don't detect colors in metadata

### ISSUE THREAD

**Issue by theflow** [opencolor-tools/js-oco-parser#13]
```js
  it("should parse metadata without detecting colors", () => {
    var test = `
group:
  oct/:
    backgroundColor: #EEEEEE
`;
    var tree = parser.parse(test);
  });
```

`Parse error on line NaN: Unexpected '#'`

I don't think it should detect a color here, just treat it as a string

**Comment by halfbyte** [comment]
Quite the contrary: The bug is that the color is not correctly parsed. We need colors (and references!) as meta values. I'll take a look.

**Comment by halfbyte** [comment]
Colors are now parsed, as well as references.
